<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>orocos_bfl_vendor</name>
  <version>2.5.1</version>
  <description> Wrapper around OpenVDB, if not found on the system, will compile from source </description>
  <maintainer email="tim.clephas@nobleo.nl">Tim Clephas</maintainer>
  <license>LGPL v2.1</license>
  <!-- The contents of this package -->
  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_vendor_package</buildtool_depend>
  <buildtool_depend>git</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
